# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/malolan/Documents/Code/Lafayette/CS 203/course-graph"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/malolan/Documents/Code/Lafayette/CS 203/course-graph"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/malolan/Documents/Code/Lafayette/CS 203/course-graph/CMakeFiles" "/Users/malolan/Documents/Code/Lafayette/CS 203/course-graph/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/malolan/Documents/Code/Lafayette/CS 203/course-graph/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named course_graph

# Build rule for target.
course_graph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 course_graph
.PHONY : course_graph

# fast build rule for target.
course_graph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/build
.PHONY : course_graph/fast

ArrayList.o: ArrayList.c.o

.PHONY : ArrayList.o

# target to build an object file
ArrayList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/ArrayList.c.o
.PHONY : ArrayList.c.o

ArrayList.i: ArrayList.c.i

.PHONY : ArrayList.i

# target to preprocess a source file
ArrayList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/ArrayList.c.i
.PHONY : ArrayList.c.i

ArrayList.s: ArrayList.c.s

.PHONY : ArrayList.s

# target to generate assembly for a file
ArrayList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/ArrayList.c.s
.PHONY : ArrayList.c.s

Degree.o: Degree.c.o

.PHONY : Degree.o

# target to build an object file
Degree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Degree.c.o
.PHONY : Degree.c.o

Degree.i: Degree.c.i

.PHONY : Degree.i

# target to preprocess a source file
Degree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Degree.c.i
.PHONY : Degree.c.i

Degree.s: Degree.c.s

.PHONY : Degree.s

# target to generate assembly for a file
Degree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Degree.c.s
.PHONY : Degree.c.s

Department.o: Department.c.o

.PHONY : Department.o

# target to build an object file
Department.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Department.c.o
.PHONY : Department.c.o

Department.i: Department.c.i

.PHONY : Department.i

# target to preprocess a source file
Department.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Department.c.i
.PHONY : Department.c.i

Department.s: Department.c.s

.PHONY : Department.s

# target to generate assembly for a file
Department.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Department.c.s
.PHONY : Department.c.s

LinkedList.o: LinkedList.c.o

.PHONY : LinkedList.o

# target to build an object file
LinkedList.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/LinkedList.c.o
.PHONY : LinkedList.c.o

LinkedList.i: LinkedList.c.i

.PHONY : LinkedList.i

# target to preprocess a source file
LinkedList.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/LinkedList.c.i
.PHONY : LinkedList.c.i

LinkedList.s: LinkedList.c.s

.PHONY : LinkedList.s

# target to generate assembly for a file
LinkedList.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/LinkedList.c.s
.PHONY : LinkedList.c.s

Parser.o: Parser.c.o

.PHONY : Parser.o

# target to build an object file
Parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Parser.c.o
.PHONY : Parser.c.o

Parser.i: Parser.c.i

.PHONY : Parser.i

# target to preprocess a source file
Parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Parser.c.i
.PHONY : Parser.c.i

Parser.s: Parser.c.s

.PHONY : Parser.s

# target to generate assembly for a file
Parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Parser.c.s
.PHONY : Parser.c.s

Test.o: Test.c.o

.PHONY : Test.o

# target to build an object file
Test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Test.c.o
.PHONY : Test.c.o

Test.i: Test.c.i

.PHONY : Test.i

# target to preprocess a source file
Test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Test.c.i
.PHONY : Test.c.i

Test.s: Test.c.s

.PHONY : Test.s

# target to generate assembly for a file
Test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Test.c.s
.PHONY : Test.c.s

Types.o: Types.c.o

.PHONY : Types.o

# target to build an object file
Types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Types.c.o
.PHONY : Types.c.o

Types.i: Types.c.i

.PHONY : Types.i

# target to preprocess a source file
Types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Types.c.i
.PHONY : Types.c.i

Types.s: Types.c.s

.PHONY : Types.s

# target to generate assembly for a file
Types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/Types.c.s
.PHONY : Types.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/course_graph.dir/build.make CMakeFiles/course_graph.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... course_graph"
	@echo "... ArrayList.o"
	@echo "... ArrayList.i"
	@echo "... ArrayList.s"
	@echo "... Degree.o"
	@echo "... Degree.i"
	@echo "... Degree.s"
	@echo "... Department.o"
	@echo "... Department.i"
	@echo "... Department.s"
	@echo "... LinkedList.o"
	@echo "... LinkedList.i"
	@echo "... LinkedList.s"
	@echo "... Parser.o"
	@echo "... Parser.i"
	@echo "... Parser.s"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
	@echo "... Types.o"
	@echo "... Types.i"
	@echo "... Types.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

